server:
  port: 9000
spring:
  application:
    name: elasticsearchExam
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300

initial-import:
  enabled: false